CREATE DATABASE IF NOT EXISTS barcode_app;
USE barcode_app;

SELECT host FROM mysql.user WHERE User = 'root';
CREATE USER 'root'@'172.19.0.3' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.19.0.3' WITH GRANT OPTION;
FLUSH PRIVILEGES;
CREATE USER 'root'@'172.19.0.4' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'172.19.0.4' WITH GRANT OPTION;
FLUSH PRIVILEGES;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;